server:
  port: 8082

spring:
  application:
    name: filter-service

  # Configurações modernas para tratamento de erros
  web:
    resources:
      add-mappings: false

  # Kafka (se for usar posteriormente)


  # Cache
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30s

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.azvtech.filter_service: INFO
    org.springframework.web: WARN